#!/bin/bash
### BEGIN INIT INFO
# Provides:          jboss
# Required-Start:    $local_fs $remote_fs $network $syslog oracle
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop JBoss AS 7
### END INIT INFO
# chkconfig: 35 92 1

## Include some script files in order to set and export environmental variables
## as well as add the appropriate executables to $PATH.
#[ -r /etc/profile.d/java.sh ] && . /etc/profile.d/java.sh
#[ -r /etc/profile.d/jboss.sh ] && . /etc/profile.d/jboss.sh
#JAVAPTH=${JAVAPTH:-"/usr/lib/jvm/jdk1.7.0_11/bin"}

JBOSS_USER="jboss"
if [ -z "$JBOSS_USER" -o "$JBOSS_USER" = "root" ]; then
  SUBIT=""
else
#  SUBIT="sudo -i -u $JBOSS_USER"
  SUBIT=""
fi

JBOSS_HOME=/opt/jboss

AS7_OPTS="$AS7_OPTS -server-config=standalone-full.xml"   ## See AS7-1625
case "$1" in
start)	
	echo "Starting Election-360..."

#	rm -rf /opt/jboss/standalone/log/ /opt/jboss/standalone/tmp/ /opt/jboss/standalone/data/
	rm -rf /opt/jboss/standalone/tmp/ 
	rm -rf /opt/jboss/standalone/data/
	rm -vrf /opt/jboss/standalone/deployments/*deployed
	rm -vrf /opt/jboss/standalone/deployments/*undeployed
	rm -vrf /opt/jboss/standalone/deployments/*failed
	rm -vrf /opt/jboss/standalone/deployments/*dodeploy
#	mv -v /opt/jboss/standalone/deployments/eos.ear /opt/jboss/standalone/deployments/eos.ear.1
#	rename -v 's/\.jar$/\.jar\.1/' /opt/jboss/standalone/deployments/*.jar
#	rename -v 's/\.1$//' /opt/jboss/standalone/deployments/com.smartmatic.ssp.module*.jar.1
#	rename -v 's/\.1$//' /opt/jboss/standalone/deployments/com.smartmatic.ems.saes_ems.module*.jar.1
#	rename -v 's/\.1$//' /opt/jboss/standalone/deployments/com.smartmatic.ems.electoral.documents.module*.jar.1
	$SUBIT /opt/jboss/bin/standalone.sh -c standalone-full.xml -b 0.0.0.0 -bmanagement=0.0.0.0 > /dev/null &
#	c=0
#	while [ $c -lt 3 ]
#	do
#		c=$(cat /opt/jboss/standalone/log/server.log 2>/dev/null | grep "Bundle started: com.smartmatic" | wc -l)
#	done
#	rename -v 's/\.1$//' /opt/jboss/standalone/deployments/*.jar.1
#	c=0
#	while [ $c -lt 15 ]
#	do
#		c=$(cat /opt/jboss/standalone/log/server.log | grep "Bundle started: com.smartmatic" | wc -l)
#	done
#	mv -v /opt/jboss/standalone/deployments/eos.ear.1 /opt/jboss/standalone/deployments/eos.ear

	echo ">>> EOS JBOSS STARTED!!!"
	;;

stop)
        $SUBIT /opt/jboss/bin/jboss-cli.sh --connect command=:shutdown
	;;	
esac
exit 0

